# Configure graphics-related settings: resolution, vsync, anti-aliasing, etc
graphics:
    # Set the window resolution, should be a either 2-element list of [width, height] in pixels or one of: 720p, 1080p
    resolution: 720p
    # Fullscreen or windowed? Valid values are: Yes, No
    fullscreen: No
    # Should vertical sync be enabled? Valid values are: Yes, No
    vsync: Yes
    # Should Full Screen Anti Aliasing be enabled? Valid values are: No, 2x, 4x, 8x, 16x
    # TODO: probably needs to be replaced with settings for FXAA and other stuff...
    fsaa: 4x
    # Shuld debug rendering be enabled? Ignored in release builds
    debug: Yes

# Configure telemetry and logging. This is a development/debug feature that should probably be disabled for release.
telemetry:
    # Development mode. Ignored in release builds, valid values are: Yes, No
    dev_mode: Yes
    # Is logging enabled? Valid values are: No or one of "trace", "debug", "info", "warn", "error"
    # In release builds, trace and debug are ignored.
    logging: trace
    # Is profiling enabled? valid values are: Yes, No
    # In release builds, profiling is ignored.
    profiling: Yes

# Configure the game
game:
    # Module files or directories for game data files and assets
    sources: ["game.module", "data/"]
    # Configuration file for the game
    game_config: game.yml
